version: '3.8'

services:
  bodilgraphapi:
    image: iqadeer/bodilenergy:bodilgraphapi-dev-1.0
    build:
      context: ./graphapi
      dockerfile: ../.docker/api.dev.Dockerfile
    environment:
      NODE_ENV: production
      SERVER_PORT: 5601
    ports:
      - 5601:5601
  bodilclient:
    image: iqadeer/bodilenergy:bodilclient-dev-1.0
    build:
      context: ./graph-client
      dockerfile: ../.docker/client.dev.Dockerfile
    environment:
      NODE_ENV: production
      SERVER_PORT: 5601
    ports:
      - 3000:80